/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import classes.NumNatural;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author roger
 */
public class TelaNumeroNatural extends javax.swing.JFrame {

    /**
     * Creates new form TelaNumeroNatural
     */
    public TelaNumeroNatural() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableNumeroNatural = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldSegundoNumNatural = new javax.swing.JTextField();
        jTextFieldPrineiroNumNatural = new javax.swing.JTextField();
        jButtonExecutar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("NumeroNatural");

        tableNumeroNatural.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Itens", "Primeiro", "Segundo"
            }
        ));
        jScrollPane1.setViewportView(tableNumeroNatural);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("Números Naturais");

        jLabel2.setText("Primeiro Número");

        jLabel3.setText("Segundo Número");

        jButtonExecutar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButtonExecutar.setText("Executar");
        jButtonExecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExecutarActionPerformed(evt);
            }
        });

        jLabel4.setText("              Operação");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldPrineiroNumNatural, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldSegundoNumNatural, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(36, 36, 36))))
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonExecutar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(107, 107, 107))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonExecutar)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldSegundoNumNatural, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldPrineiroNumNatural, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void jButtonExecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExecutarActionPerformed

        try {
            NumNatural primeiro = new NumNatural();
            primeiro.setNumero(Long.parseLong(jTextFieldPrineiroNumNatural.getText()));
           // int valor = (Integer.parseInt(jTextFieldPrineiroNumNatural.getText()));
            
            NumNatural segundo = new NumNatural(Long.parseLong(jTextFieldSegundoNumNatural.getText()));
            
            NumNatural terceiro = new NumNatural(segundo);       
            

            DefaultTableModel model = (DefaultTableModel) tableNumeroNatural.getModel();
            String[] linha = new String[]{"", "", ""};
            linha[0] = "FATORIAL";
            linha[1] = "" + primeiro.calcularFatorial().getNumero();
            linha[2] = "" + segundo.calcularFatorial().getNumero();
            model.addRow(linha);

        
            linha[0] = "NUMERO PERFEITO";
            if (primeiro.eNumeroPerfeito() == true) {
                linha[1] = "SIM";
            } else {
                linha[1] = "NÃO";
            }
            if (segundo.eNumeroPerfeito() == true) {
                linha[2] = "SIM";
            } else {
                linha[2] = "NÃO";
            }
            model.addRow(linha);

            linha[0] = "CAPICUA";
            if (primeiro.eCapicua() == true) {
                linha[1] = "SIM";
            } else {
                linha[1] = "NÃO";
            }
            if (segundo.eCapicua() == true) {
                linha[2] = "SIM";
            } else {
                linha[2] = "NÃO";
            }
            model.addRow(linha);

            linha[0] = "QUADRADO PERFEITO";
            if (primeiro.eQuadradoPerfeito() == true) {
                linha[1] = "SIM";
            } else {
                linha[1] = "NÃO";
            }
            if (segundo.eQuadradoPerfeito() == true) {
                linha[2] = "SIM";
            } else {
                linha[2] = "NÃO";
            }
            model.addRow(linha);

            linha[0] = "NÚMERO PRIMO";
            if (primeiro.eNumeroPrimo() == true) {
                linha[1] = "SIM";
            } else {
                linha[1] = "NÃO";
            }
            if (segundo.eNumeroPrimo() == true) {
                linha[2] = "SIM";
            } else {
                linha[2] = "NÃO";
            }
            model.addRow(linha);

            linha[0] = "BASE 10 PARA BASE 2";
            linha[1] = "" + primeiro.mudarBase( 2);
            linha[2] = "" + segundo.mudarBase( 2);
            model.addRow(linha);

            linha[0] = "BASE 10 PARA BASE 8";
            linha[1] = "" + primeiro.mudarBase( 8);
            linha[2] = "" + segundo.mudarBase(8);
            model.addRow(linha);

            linha[0] = "BASE 10 PARA BASE 16";
            linha[1] = "" + primeiro.mudarBase(16);
            linha[2] = "" + segundo.mudarBase(16);
            model.addRow(linha);

            linha[0] = "MAXIMO DIVISOR COMUM";
            linha[1] = "" + primeiro.calcularMDC(segundo).getNumero();
            linha[2] = "" + segundo.calcularMDC(primeiro).getNumero();
            model.addRow(linha);

            linha[0] = "MÍNIMO MÚLTIPLO COMUM";
            linha[1] = "" + primeiro.calcularMMC(segundo).getNumero();
            linha[2] = "" + segundo.calcularMMC(primeiro).getNumero();
            model.addRow(linha);

            linha[0] = "PRIMO ENTRE SI";
            if (primeiro.PrimoEntreSi(segundo) == true) {
                linha[1] = "SIM";
            } else {
                linha[1] = "NÃO";
            }
            if (segundo.PrimoEntreSi(primeiro) == true) {
                linha[2] = "SIM";
            } else {
                linha[2] = "NÃO";
            }
            model.addRow(linha);

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(rootPane, erro.getMessage());
        }
        /*
public static void alinhaTableCentro(JTable table, int[] posicoesDireita) {

	DefaultTableCellRenderer cellRender = new DefaultTableCellRenderer();
	cellRender.setHorizontalAlignment(SwingConstants.CENTER);

	for (int numCol = 0; numCol < table.getColumnCount(); numCol++) {

		for (int i = 0; i < posicoesDireita.length; i++) {

			if (numCol == posicoesDireita[i]) {

				table.getColumnModel().getColumn(numCol).setCellRenderer(
						cellRender);
			}
		}
	}
}*/

    }//GEN-LAST:event_jButtonExecutarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaNumeroNatural.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaNumeroNatural.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaNumeroNatural.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaNumeroNatural.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaNumeroNatural().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonExecutar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldPrineiroNumNatural;
    private javax.swing.JTextField jTextFieldSegundoNumNatural;
    private javax.swing.JTable tableNumeroNatural;
    // End of variables declaration//GEN-END:variables
}
